import glob
import os
import re
import sys
import time
import uuid
from typing import Any, Dict, List

import requests


class BaseProvider:
    """Common provider configuration."""

    USER_AGENT = (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/133.0.0.0 Safari/537.36"
    )

    TIMEOUT = 30

    def __init__(self, name: str) -> None:
        self.name = name

    def get_user_agent(self) -> str:
        return self.USER_AGENT

    def get_timeout(self) -> int:
        return self.TIMEOUT


class PlutoProvider(BaseProvider):
    """Fetch Pluto TV channels and generate regional M3U playlists."""

    START_URL = "https://boot.pluto.tv/v4/start"

    CHANNELS_URL = (
        "https://service-channels.clusters.pluto.tv/v2/guide/channels"
    )

    CATEGORIES_URL = (
        "https://service-channels.clusters.pluto.tv/v2/guide/categories"
    )

    STITCHER_BASE_URL = (
        "https://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv"
        "/v2/stitch/hls/channel"
    )

    EPG_BASE_URL = (
        "https://github.com/matthuisman/i.mjh.nz/raw/master/PlutoTV"
    )

    QUALITY_PARAMS = (
        "quality=720p"
        "&deviceMake=chrome"
        "&deviceType=web"
        "&deviceModel=web"
        "&deviceVersion=133.0.0"
        "&architecture=x86_64"
        "&buildVersion=1.0.0"
        "&includeExtendedEvents=true"
        "&masterJWTPassthrough=true"
    )

    # Regions currently generated by the GitHub Actions workflow.
    VALID_REGIONS = {
        "us",
        "ca",
        "gb",
        "de",
        "mx",
        "no",
        "se",
        "dk",
    }

    def __init__(self) -> None:
        super().__init__("pluto")

        self.device_id = str(uuid.uuid4())
        self.session_token = ""
        self.stitcher_params = ""
        self.session_expires_at = 0.0

        self.region = os.getenv("PLUTO_REGION", "us").strip().lower()

        if self.region not in self.VALID_REGIONS:
            raise ValueError(
                f"Unsupported PLUTO_REGION '{self.region}'. "
                f"Supported regions: "
                f"{', '.join(sorted(self.VALID_REGIONS))}"
            )

        self.headers = {
            "accept": "*/*",
            "accept-language": "en-US,en;q=0.9",
            "origin": "https://pluto.tv",
            "referer": "https://pluto.tv/",
            "user-agent": self.get_user_agent(),
        }

        self.session = requests.Session()
        self.session.headers.update(self.headers)

    def _get_session_token(self) -> str:
        """Get a Pluto session token, refreshing it when necessary."""

        now = time.time()

        if self.session_token and now < self.session_expires_at:
            return self.session_token

        params = {
            "appName": "web",
            "appVersion": "8.1.0",
            "deviceVersion": "133.0.0",
            "deviceModel": "web",
            "deviceMake": "chrome",
            "deviceType": "web",
            "clientID": self.device_id,
            "clientModelNumber": "1.0.0",
            "serverSideAds": "false",
            "architecture": "x86_64",
            "buildVersion": "1.0.0",
            "drmCapabilities": "widevine:L3",
        }

        try:
            response = self.session.get(
                self.START_URL,
                params=params,
                timeout=self.get_timeout(),
            )

            response.raise_for_status()

            data = response.json()

            token = data.get("sessionToken", "")
            stitcher_params = data.get("stitcherParams", "")

            if not token:
                raise RuntimeError(
                    "Pluto did not return a session token."
                )

            self.session_token = token
            self.stitcher_params = stitcher_params

            # Refresh slightly before the nominal four-hour expiration.
            self.session_expires_at = time.time() + (3.5 * 3600)

            return self.session_token

        except requests.RequestException as exc:
            raise RuntimeError(
                f"Failed to obtain Pluto session token: {exc}"
            ) from exc

        except ValueError as exc:
            raise RuntimeError(
                "Pluto returned invalid JSON while requesting a session token."
            ) from exc

    def _get_categories(
        self,
        headers: Dict[str, str],
    ) -> Dict[str, str]:
        """Return a mapping of channel ID to category name."""

        try:
            response = self.session.get(
                self.CATEGORIES_URL,
                headers=headers,
                timeout=self.get_timeout(),
            )

            response.raise_for_status()

            data = response.json().get("data", [])

            category_map: Dict[str, str] = {}

            for category in data:
                category_name = category.get("name", "General")

                for channel_id in category.get("channelIDs", []):
                    category_map[str(channel_id)] = category_name

            return category_map

        except requests.RequestException as exc:
            raise RuntimeError(
                f"Failed to retrieve Pluto categories: {exc}"
            ) from exc

        except ValueError as exc:
            raise RuntimeError(
                "Pluto returned invalid JSON while retrieving categories."
            ) from exc

    def get_channels(self) -> List[Dict[str, Any]]:
        """Fetch and process all Pluto channels for the selected region."""

        token = self._get_session_token()

        if not token:
            raise RuntimeError(
                "No Pluto session token was available."
            )

        headers = self.headers.copy()
        headers["authorization"] = f"Bearer {token}"

        try:
            response = self.session.get(
                self.CHANNELS_URL,
                params={"limit": "1000"},
                headers=headers,
                timeout=self.get_timeout(),
            )

            response.raise_for_status()

            channel_data = response.json().get("data", [])

        except requests.RequestException as exc:
            raise RuntimeError(
                f"Failed to retrieve Pluto channels for region "
                f"{self.region}: {exc}"
            ) from exc

        except ValueError as exc:
            raise RuntimeError(
                f"Pluto returned invalid channel data for region "
                f"{self.region}."
            ) from exc

        if not channel_data:
            raise RuntimeError(
                f"Pluto returned zero channels for region "
                f"'{self.region}'."
            )

        categories = self._get_categories(headers)

        processed_channels: List[Dict[str, Any]] = []

        for channel in channel_data:
            channel_id = channel.get("id")
            name = channel.get("name")

            if not channel_id or not name:
                continue

            logo = next(
                (
                    image.get("url")
                    for image in channel.get("images", [])
                    if image.get("type") == "colorLogoPNG"
                    and image.get("url")
                ),
                "",
            )

            group = categories.get(
                str(channel_id),
                "Pluto TV",
            )

            stream_url = (
                f"{self.STITCHER_BASE_URL}/{channel_id}/master.m3u8"
                f"?{self.stitcher_params}"
                f"&jwt={token}"
                f"&{self.QUALITY_PARAMS}"
            )

            processed_channels.append(
                {
                    "id": str(channel_id),
                    "name": name,
                    "stream_url": stream_url,
                    "logo": logo,
                    "group": group,
                }
            )

        if not processed_channels:
            raise RuntimeError(
                f"No usable channels were returned for region "
                f"'{self.region}'."
            )

        return processed_channels

    def generate_m3u(
        self,
        channels: List[Dict[str, Any]],
    ) -> str:
        """Generate an M3U playlist for the current region."""

        epg_url = f"{self.EPG_BASE_URL}/{self.region}.xml.gz"

        lines = [
            f'#EXTM3U url-tvg="{epg_url}"'
        ]

        for channel in channels:
            name = self._escape_m3u_value(channel["name"])
            channel_id = self._escape_m3u_value(channel["id"])
            logo = self._escape_m3u_value(channel["logo"])
            group = self._escape_m3u_value(channel["group"])

            lines.append(
                f'#EXTINF:-1 '
                f'tvg-id="{channel_id}" '
                f'tvg-logo="{logo}" '
                f'group-title="{group}",'
                f'{name}'
            )

            lines.append(channel["stream_url"])

        return "\n".join(lines) + "\n"

    @staticmethod
    def _escape_m3u_value(value: str) -> str:
        """Prevent quotes/newlines from breaking M3U attributes."""

        return (
            str(value)
            .replace('"', "'")
            .replace("\r", "")
            .replace("\n", " ")
        )

    def write_playlist(
        self,
        channels: List[Dict[str, Any]],
    ) -> str:
        """Write the regional playlist to disk."""

        filename = f"pluto_{self.region}.m3u"
        content = self.generate_m3u(channels)

        with open(
            filename,
            "w",
            encoding="utf-8",
            newline="\n",
        ) as playlist:
            playlist.write(content)

        return filename


# Only the regions currently generated by the workflow.
COUNTRIES = {
    "us": {
        "priority": 1,
        "label": "United States",
    },
    "ca": {
        "priority": 2,
        "label": "Canada",
    },
    "gb": {
        "priority": 3,
        "label": "United Kingdom",
    },
    "de": {
        "priority": 4,
        "label": "Germany",
    },
    "mx": {
        "priority": 5,
        "label": "Mexico",
    },
    "no": {
        "priority": 6,
        "label": "Norway",
    },
    "se": {
        "priority": 7,
        "label": "Sweden",
    },
    "dk": {
        "priority": 8,
        "label": "Denmark",
    },
}


def merge_master_playlist() -> None:
    """Combine regional playlists into pluto_all.m3u."""

    playlist_files = []

    for filename in glob.glob("pluto_*.m3u"):
        region = (
            filename
            .removeprefix("pluto_")
            .removesuffix(".m3u")
        )

        if region in COUNTRIES:
            playlist_files.append(filename)

    playlist_files.sort(
        key=lambda filename: COUNTRIES[
            filename
            .removeprefix("pluto_")
            .removesuffix(".m3u")
        ]["priority"]
    )

    if not playlist_files:
        raise RuntimeError(
            "No regional Pluto playlists were found to merge."
        )

    master_lines = [
        f'#EXTM3U url-tvg="{PlutoProvider.EPG_BASE_URL}/all.xml.gz"'
    ]

    total_channels = 0

    for filename in playlist_files:
        region = (
            filename
            .removeprefix("pluto_")
            .removesuffix(".m3u")
        )

        country_label = COUNTRIES[region]["label"]

        with open(
            filename,
            "r",
            encoding="utf-8",
        ) as playlist:

            for line in playlist:
                line = line.rstrip("\r\n")

                if not line or line.startswith("#EXTM3U"):
                    continue

                if line.startswith("#EXTINF"):
                    line = re.sub(
                        r'group-title="[^"]*"',
                        f'group-title="{country_label}"',
                        line,
                    )

                    master_lines.append(line)
                    total_channels += 1

                else:
                    master_lines.append(line)

    if total_channels == 0:
        raise RuntimeError(
            "The master playlist would contain zero channels. "
            "Refusing to write an empty master playlist."
        )

    with open(
        "pluto_all.m3u",
        "w",
        encoding="utf-8",
        newline="\n",
    ) as playlist:
        playlist.write(
            "\n".join(master_lines) + "\n"
        )

    print(
        f"Created pluto_all.m3u with "
        f"{total_channels} channels from "
        f"{len(playlist_files)} regional playlists."
    )


def update_region() -> None:
    """Fetch channels and write the regional playlist."""

    provider = PlutoProvider()

    print(
        f"Fetching Pluto channels for region: "
        f"{provider.region.upper()}"
    )

    channels = provider.get_channels()

    print(
        f"Received {len(channels)} channels for region "
        f"{provider.region.upper()}."
    )

    filename = provider.write_playlist(channels)

    print(f"Created {filename}")


def main() -> None:
    """Program entry point."""

    if len(sys.argv) > 1:
        if sys.argv[1] == "--merge":
            merge_master_playlist()
            return

        raise SystemExit(
            f"Unknown argument: {sys.argv[1]}\n"
            "Usage: python pluto_provider.py [--merge]"
        )

    update_region()


if __name__ == "__main__":
    try:
        main()

    except KeyboardInterrupt:
        print("\nOperation cancelled.")
        sys.exit(130)

    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
